on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  contributors:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: List contributors
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get contributors
        uses: ./
        id: contributors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          org: 'hugomods'
          output: 'data/contributors.toml'

      - run: cat data/contributors.toml

      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: "chore: update data/contributors.toml"
      #     file_pattern: 'data/contributors.toml'
